// <auto-generated />
using System;
using Easrms.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Easrms.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260603100106_Inital_PostgraceSQl")]
    partial class Inital_PostgraceSQl
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Easrms.Domain.Entities.RequestCategory", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("category_name");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_on");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsApprovalRequired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_approval_required");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<int>("SLAHours")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(24)
                        .HasColumnName("sla_hours");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on");

                    b.HasKey("CategoryId")
                        .HasName("pk_request_categories");

                    b.HasIndex("CategoryName")
                        .IsUnique()
                        .HasDatabaseName("ix_request_categories_category_name");

                    b.ToTable("request_categories", (string)null);
                });

            modelBuilder.Entity("Easrms.Domain.Entities.RequestComment", b =>
                {
                    b.Property<Guid>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("comment_id");

                    b.Property<Guid>("CommentBy")
                        .HasColumnType("uuid")
                        .HasColumnName("comment_by");

                    b.Property<string>("CommentText")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("comment_text");

                    b.Property<int>("CommentType")
                        .HasColumnType("integer")
                        .HasColumnName("comment_type");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("request_id");

                    b.HasKey("CommentId")
                        .HasName("pk_request_comments");

                    b.HasIndex("CommentBy")
                        .HasDatabaseName("ix_request_comments_comment_by");

                    b.HasIndex("RequestId")
                        .HasDatabaseName("ix_request_comments_request_id");

                    b.ToTable("request_comments", (string)null);
                });

            modelBuilder.Entity("Easrms.Domain.Entities.RequestEscalationHistory", b =>
                {
                    b.Property<Guid>("EscalationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("escalation_id");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<Guid>("EscalatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("escalated_by");

                    b.Property<DateTime>("EscalatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("escalated_on");

                    b.Property<string>("EscalationReason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("escalation_reason");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("request_id");

                    b.HasKey("EscalationId")
                        .HasName("pk_request_escalation_histories");

                    b.HasIndex("EscalatedBy")
                        .HasDatabaseName("ix_request_escalation_histories_escalated_by");

                    b.HasIndex("RequestId")
                        .HasDatabaseName("ix_request_escalation_histories_request_id");

                    b.ToTable("request_escalation_histories", (string)null);
                });

            modelBuilder.Entity("Easrms.Domain.Entities.RequestStatusHistory", b =>
                {
                    b.Property<Guid>("HistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("history_id");

                    b.Property<Guid>("ChangedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("changed_by");

                    b.Property<DateTime>("ChangedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_on");

                    b.Property<int>("NewStatus")
                        .HasMaxLength(30)
                        .HasColumnType("integer")
                        .HasColumnName("new_status");

                    b.Property<int?>("OldStatus")
                        .HasMaxLength(30)
                        .HasColumnType("integer")
                        .HasColumnName("old_status");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("remarks");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("request_id");

                    b.HasKey("HistoryId")
                        .HasName("pk_request_status_histories");

                    b.HasIndex("ChangedBy")
                        .HasDatabaseName("ix_request_status_histories_changed_by");

                    b.HasIndex("RequestId")
                        .HasDatabaseName("ix_request_status_histories_request_id");

                    b.ToTable("request_status_histories", (string)null);
                });

            modelBuilder.Entity("Easrms.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role_name");

                    b.HasKey("RoleId")
                        .HasName("pk_roles");

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            RoleId = new Guid("90a5eb56-0ddc-4187-9f32-8870f8fc7043"),
                            RoleName = "Admin"
                        },
                        new
                        {
                            RoleId = new Guid("90a5eb56-0ddc-4187-9f32-8870f8fc7044"),
                            RoleName = "Manager"
                        },
                        new
                        {
                            RoleId = new Guid("90a5eb56-0ddc-4187-9f32-8870f8fc7045"),
                            RoleName = "Employee"
                        },
                        new
                        {
                            RoleId = new Guid("90a5eb56-0ddc-4187-9f32-8870f8fc7046"),
                            RoleName = "Support"
                        });
                });

            modelBuilder.Entity("Easrms.Domain.Entities.ServiceRequest", b =>
                {
                    b.Property<Guid>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("request_id");

                    b.Property<Guid?>("AssignedTo")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_to");

                    b.Property<string>("AttachmentUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("attachment_url");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<Guid?>("ClosedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("closed_by");

                    b.Property<DateTime?>("ClosedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_on");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_date");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<Guid?>("EscalatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("escalated_by");

                    b.Property<DateTime?>("EscalatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("escalated_on");

                    b.Property<string>("EscalationReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("escalation_reason");

                    b.Property<bool>("IsEscalated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_escalated");

                    b.Property<int>("Priority")
                        .HasMaxLength(20)
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("rejection_reason");

                    b.Property<string>("RequestNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("request_number");

                    b.Property<DateTime?>("ResolvedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_on");

                    b.Property<int>("Status")
                        .HasMaxLength(30)
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on");

                    b.HasKey("RequestId")
                        .HasName("pk_service_requests");

                    b.HasIndex("AssignedTo")
                        .HasDatabaseName("ix_service_requests_assigned_to");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_service_requests_category_id");

                    b.HasIndex("ClosedBy")
                        .HasDatabaseName("ix_service_requests_closed_by");

                    b.HasIndex("EmployeeId")
                        .HasDatabaseName("ix_service_requests_employee_id");

                    b.HasIndex("EscalatedBy")
                        .HasDatabaseName("ix_service_requests_escalated_by");

                    b.HasIndex("RequestNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_service_requests_request_number");

                    b.ToTable("service_requests", (string)null);
                });

            modelBuilder.Entity("Easrms.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_on");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("LastLoginOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_on");

                    b.Property<Guid?>("ManagerId")
                        .HasColumnType("uuid")
                        .HasColumnName("manager_id");

                    b.Property<string>("OtpCode")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("otp_code");

                    b.Property<DateTime?>("OtpExpiryOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("otp_expiry_on");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("ProfilePhotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("profile_photo_url");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("refresh_token");

                    b.Property<DateTime?>("RefreshTokenExpiryOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("refresh_token_expiry_on");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on");

                    b.HasKey("UserId")
                        .HasName("pk_users");

                    b.HasIndex("ManagerId")
                        .HasDatabaseName("ix_users_manager_id");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_users_role_id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Easrms.Domain.Entities.UserAuthProvider", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AuthProvider")
                        .HasColumnType("integer")
                        .HasColumnName("auth_provider");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<string>("ExternalUserId")
                        .HasColumnType("text")
                        .HasColumnName("external_user_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_auth_providers");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_auth_providers_user_id");

                    b.ToTable("user_auth_providers", (string)null);
                });

            modelBuilder.Entity("Easrms.Domain.Entities.RequestComment", b =>
                {
                    b.HasOne("Easrms.Domain.Entities.User", "CommentByUser")
                        .WithMany("Comments")
                        .HasForeignKey("CommentBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_request_comments_users_comment_by");

                    b.HasOne("Easrms.Domain.Entities.ServiceRequest", "ServiceRequest")
                        .WithMany("Comments")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_request_comments_service_requests_request_id");

                    b.Navigation("CommentByUser");

                    b.Navigation("ServiceRequest");
                });

            modelBuilder.Entity("Easrms.Domain.Entities.RequestEscalationHistory", b =>
                {
                    b.HasOne("Easrms.Domain.Entities.User", "EscalatedByUser")
                        .WithMany()
                        .HasForeignKey("EscalatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_request_escalation_histories_users_escalated_by");

                    b.HasOne("Easrms.Domain.Entities.ServiceRequest", "Request")
                        .WithMany("EscalationHistories")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_request_escalation_histories_service_requests_request_id");

                    b.Navigation("EscalatedByUser");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("Easrms.Domain.Entities.RequestStatusHistory", b =>
                {
                    b.HasOne("Easrms.Domain.Entities.User", "ChangedByUser")
                        .WithMany("StatusHistories")
                        .HasForeignKey("ChangedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_request_status_histories_users_changed_by");

                    b.HasOne("Easrms.Domain.Entities.ServiceRequest", "Request")
                        .WithMany("StatusHistories")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_request_status_histories_service_requests_request_id");

                    b.Navigation("ChangedByUser");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("Easrms.Domain.Entities.ServiceRequest", b =>
                {
                    b.HasOne("Easrms.Domain.Entities.User", "AssignedUser")
                        .WithMany("AssignedRequests")
                        .HasForeignKey("AssignedTo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_service_requests_users_assigned_to");

                    b.HasOne("Easrms.Domain.Entities.RequestCategory", "Category")
                        .WithMany("ServiceRequests")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_service_requests_request_categories_category_id");

                    b.HasOne("Easrms.Domain.Entities.User", "ClosedByUser")
                        .WithMany("ClosedRequests")
                        .HasForeignKey("ClosedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_service_requests_users_closed_by");

                    b.HasOne("Easrms.Domain.Entities.User", "Employee")
                        .WithMany("CreatedRequests")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_service_requests_users_employee_id");

                    b.HasOne("Easrms.Domain.Entities.User", "Escalator")
                        .WithMany()
                        .HasForeignKey("EscalatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_service_requests_users_escalated_by");

                    b.Navigation("AssignedUser");

                    b.Navigation("Category");

                    b.Navigation("ClosedByUser");

                    b.Navigation("Employee");

                    b.Navigation("Escalator");
                });

            modelBuilder.Entity("Easrms.Domain.Entities.User", b =>
                {
                    b.HasOne("Easrms.Domain.Entities.User", "Manager")
                        .WithMany("Employees")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_users_users_manager_id");

                    b.HasOne("Easrms.Domain.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_users_roles_role_id");

                    b.Navigation("Manager");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Easrms.Domain.Entities.UserAuthProvider", b =>
                {
                    b.HasOne("Easrms.Domain.Entities.User", "User")
                        .WithMany("AuthProviders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_auth_providers_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Easrms.Domain.Entities.RequestCategory", b =>
                {
                    b.Navigation("ServiceRequests");
                });

            modelBuilder.Entity("Easrms.Domain.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Easrms.Domain.Entities.ServiceRequest", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("EscalationHistories");

                    b.Navigation("StatusHistories");
                });

            modelBuilder.Entity("Easrms.Domain.Entities.User", b =>
                {
                    b.Navigation("AssignedRequests");

                    b.Navigation("AuthProviders");

                    b.Navigation("ClosedRequests");

                    b.Navigation("Comments");

                    b.Navigation("CreatedRequests");

                    b.Navigation("Employees");

                    b.Navigation("StatusHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
